action: DatasetVocabBuilder
dataset_files: ["outputs/datasets/train",
                "outputs/datasets/valid",
                "outputs/datasets/test"]

vocab_file: outputs/datasets/vocab.json
pad_token: <pad>
unk_token: <unk>
