action: Prediction
image_size: [112, 112]

encoder:
  configFile: configs/resnet_encoder.yaml

model:
  saved: outputs/runs/resnet_gru_model/best.pt
  checkpoint: null

vocab:
  file: outputs/datasets/vocab.json
