action: Training
name: resnet_lstm
n_epochs: 200
report_dir: outputs/runs/
savedModel: outputs/resnet_lstm.pt
savingStep: 5

optim:
  learning_rate: 0.001
  beta: [0.9, 0.98]
  eps: 0.000000001

checkpoint:
  folder: outputs/transformer_ckp/
  last_ckp_count: 3

dataset:
  train: outputs/dataset_norm/train
  valid: outputs/dataset_norm/valid
  test: outputs/dataset_norm/test
  batch_size: 64
  n_workers: 4

model:
  configFile: configs/resnet_lstm.yaml
  vocab_file: outputs/datasets/vocab.json
