action: Training
name: resnet_gru
n_epochs: 200
report_dir: outputs/runs/
savedModel: outputs/resnet_lstm.pt

optim:
  learning_rate: 0.001
  beta: [0.9, 0.98]
  eps: 0.000000001

checkpoint:
  folder: outputs/resnet_gru_ckp/
  last_ckp_count: 3

dataset:
  train: outputs/dataset_norm/train
  valid: outputs/dataset_norm/valid
  test: outputs/dataset_norm/test
  batch_size: 32
  n_workers: 2

model:
  decoder:
    configFile: configs/resnet_encoder.yaml
  vocab_file: outputs/datasets/vocab.json
